version: '3.8'

services:
  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: ecommerce-netapp-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ecommerce-network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: ecommerce-db-admin
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    restart: unless-stopped
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
  litedb_data:
  api_logs:

networks:
  ecommerce-network:
    driver: bridge